/*
 * The Travelforge Project
 * http://www.travelforge.org
 *
 * Copyright (c) 2015 - 2017 Matthias Deck
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.travelforge.product.service;

/**
 * @author Matthias Deck
 */
public enum PackageRequestParameterName implements PackageRequestParameterMapKey {

    PRODUCT_GROUPS,
    TOUR_OPERATOR_CODES,
    TRAVELLERS_ADULTS,
    TRAVELLERS_CHILDREN_AGE,
    TRAVELLERS_CHILDREN_DATE_OF_BIRTH,
    TRAVEL_PERIOD_DEPARTURE_DATE,
    TRAVEL_PERIOD_DEPARTURE_DATE_OFFSET,
    TRAVEL_PERIOD_DEPARTURE_DATE_PRE_OFFSET,
    TRAVEL_PERIOD_DEPARTURE_DATE_POST_OFFSET,
    TRAVEL_PERIOD_DEPARTURE_DAYS,
    TRAVEL_PERIOD_DEPARTURE_TIME_MIN,
    TRAVEL_PERIOD_DEPARTURE_TIME_MAX,
    TRAVEL_PERIOD_RETURN_DATE,
    TRAVEL_PERIOD_RETURN_DATE_OFFSET,
    TRAVEL_PERIOD_RETURN_DATE_PRE_OFFSET,
    TRAVEL_PERIOD_RETURN_DATE_POST_OFFSET,
    TRAVEL_PERIOD_RETURN_DAYS,
    TRAVEL_PERIOD_RETURN_TIME_MIN,
    TRAVEL_PERIOD_RETURN_TIME_MAX,
    TRAVEL_PERIOD_DURATIONS,
    FLIGHT_DEPARTURE_AIRPORT_CODES,
    FLIGHT_ARRIVAL_AIRPORT_CODES,
    FLIGHT_AIRLINE_CODES,
    FLIGHT_STOP_OVER_MAX,
    HOTEL_CODES,
    HOTEL_PRODUCT_CODES,
    HOTEL_CATEGORY,
    HOTEL_LOCATION_COUNTRY_CODES,
    HOTEL_LOCATION_REGION_CODES,
    HOTEL_LOCATION_CITY_CODES,
    HOTEL_ATTRIBUTES,
    HOTEL_RATING_COUNT,
    HOTEL_RATING_OVERALL,
    HOTEL_RATING_TOTAL,
    HOTEL_RATING_HOTEL,
    HOTEL_RATING_LOCATION,
    HOTEL_RATING_SERVICE,
    HOTEL_RATING_CATERING,
    HOTEL_RATING_SPORT,
    HOTEL_RATING_ROOM,
    HOTEL_RECOMMENDATIONS_TOTAL,
    HOTEL_RECOMMENDATIONS_SINGLE,
    HOTEL_RECOMMENDATIONS_FAMILY,
    HOTEL_RECOMMENDATIONS_COUPLES,
    HOTEL_RECOMMENDATIONS_FRIENDS,
    HOTEL_RECOMMENDATIONS_BEACH_HOLIDAY,
    HOTEL_RECOMMENDATIONS_BUSINESS_TRIP,
    HOTEL_RECOMMENDATIONS_CITY_BREAK,
    HOTEL_RECOMMENDATIONS_WELLNESS,
    HOTEL_ROOM_CODES,
    HOTEL_ROOM_BOOKING_CODES,
    HOTEL_ROOM_VIEW_CODES,
    HOTEL_ROOM_ATTRIBUTES,
    HOTEL_BOARD_CODES,
    EXTRAS,
    PRICE_MIN,
    PRICE_MAX
}
